# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: MATLAB

on:
  push:
    paths:
      - '.github/workflows/matlab.yml'
      - 'ci/scripts/matlab*.sh'
      - 'matlab/**'
      - 'cpp/src/arrow/**'
  pull_request:
    paths:
      - '.github/workflows/matlab.yml'
      - 'ci/scripts/matlab*.sh'
      - 'matlab/**'
      - 'cpp/src/arrow/**'

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    name: AMD64 Windows 2022 MATLAB
    runs-on: windows-2022
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    steps:
      - name: Check out repository        
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023b
      - name: Download Timezone Database
        shell: bash
        run: ci/scripts/download_tz_database.sh
      - name: Install ccache
        shell: bash
        run: ci/scripts/install_ccache.sh 4.6.3 /usr
      - name: Setup ccache
        shell: bash
        run: ci/scripts/ccache_setup.sh
      - name: ccache info
        id: ccache-info
        shell: bash
        run: echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
      - name: Cache ccache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.ccache-info.outputs.cache-dir }}
          key: matlab-ccache-windows-${{ hashFiles('cpp/**', 'matlab/**') }}
          restore-keys: matlab-ccache-windows-
      - name: Build MATLAB Interface
        shell: cmd
        run: |
          cmake -S .\matlab -B .\matlab\build -G Ninja -D CMAKE_INSTALL_PREFIX=.\matlab\install -D MATLAB_ADD_INSTALL_DIR_TO_SEARCH_PATH=OFF
          cmake --build .\matlab\build --config Release --target install
      - name: Run MATLAB Tests
        env:
          # Add the installation directory to the MATLAB Search Path by
          # setting the MATLABPATH environment variable.
          MATLABPATH: matlab/install/arrow_matlab
        uses: matlab-actions/run-tests@v1
        with:
          select-by-folder: matlab/test 
